# This file was generated by GoReleaser. DO NOT EDIT.
cask "ls3" do
  name "ls3"
  desc "A terminal-based user interface for browsing Amazon S3 buckets and objects"
  homepage "https://github.com/erikmartino/ls3"
  version "1.4.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ls3"

  on_macos do
    on_intel do
      url "https://github.com/erikmartino/ls3/releases/download/v#{version}/ls3_Darwin_x86_64.tar.gz"
      sha256 "ffcffea95eacde90c65438e6e7ca94d71fc83b692f4c3137a2b0e5c2b01241de"
    end
    on_arm do
      url "https://github.com/erikmartino/ls3/releases/download/v#{version}/ls3_Darwin_arm64.tar.gz"
      sha256 "d85d9beecc0dd2283d2cd89167f33bc3d7f54819fe5323eb977ee3dafec2edeb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/erikmartino/ls3/releases/download/v#{version}/ls3_Linux_x86_64.tar.gz"
      sha256 "204284e375670a20c82c6a243bfdaaeb0c144012c361f6550ab577a898939cf9"
    end
    on_arm do
      url "https://github.com/erikmartino/ls3/releases/download/v#{version}/ls3_Linux_arm64.tar.gz"
      sha256 "4d89b33695cc53715bdfd8ceed57d938400c66272b0a2cfb4e67489cd644721e"
    end
  end

  # No zap stanza required
end
