# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ls3 < Formula
  desc "A terminal-based user interface for browsing Amazon S3 buckets and objects"
  homepage "https://github.com/erikmartino/ls3"
  version "1.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/erikmartino/ls3/releases/download/v1.4.2/ls3_Darwin_x86_64.tar.gz"
      sha256 "d70e3a3342e107d82105a46a70fdb6773e1d4cf07fe6cc18c5928ed5d0549ae2"

      def install
        bin.install "ls3"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/erikmartino/ls3/releases/download/v1.4.2/ls3_Darwin_arm64.tar.gz"
      sha256 "3b17296e249cb369856da61405059637e9e42d04c2e4d54ee2fbfd36501fe75d"

      def install
        bin.install "ls3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/erikmartino/ls3/releases/download/v1.4.2/ls3_Linux_x86_64.tar.gz"
      sha256 "2c078d363bee74fb8ef67bdba19e727b60f1e585b1f93ff4234bd32a63563b96"
      def install
        bin.install "ls3"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/erikmartino/ls3/releases/download/v1.4.2/ls3_Linux_arm64.tar.gz"
      sha256 "7a47eb6b325fd3c0ff8e38bd376c3c9cdf64bac411176602f82d0a53477ac2a7"
      def install
        bin.install "ls3"
      end
    end
  end

  test do
    system "#{bin}/ls3", "--help"
  end
end
